services:

  #  Postgres
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order-processing-system
    healthcheck:
      # We need to pass the user and database argument (user follows "-U" param and db follows "-d" param):
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "order-processing-system"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #  Kafka
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka

  #  Config-server
  config-server:
    image: ivangorbunovv/config-server-order-processing-system-image
    ports:
      - "8888:8888"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.cloud.config.server.git.username" : "GorbunovIvan",
          "spring.cloud.config.server.git.password" : ""
      }'

  #  Eureka-server
  eureka-server:
    depends_on:
      - config-server
    image: ivangorbunovv/eureka-server-order-processing-system-image
    ports:
      - "8761:8761"

  #  Api-gateway
  api-gateway:
    depends_on:
      - config-server
      - eureka-server
    image: ivangorbunovv/api-gateway-order-processing-system-image
    ports:
      - "8765:8765"

  #  Order-registrar-service
  order-registrar-service:
    depends_on:
      - kafka
      - config-server
      - eureka-server
      - api-gateway
    image: ivangorbunovv/registrar-service-order-processing-system-image
    ports:
      - "8081:8081"

  #  Order-demonstrator-service
  order-demonstrator-service:
    depends_on:
      - postgres-db
      - kafka
      - config-server
      - eureka-server
      - api-gateway
    image: ivangorbunovv/demonstrator-service-order-processing-system-image
    ports:
      - "8082:8082"

volumes:
  postgres-data:
    driver: local
  kafka-data:
    driver: local
