server:
  port: 8081

spring:
  application:
    name: order-demonstrator-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order-processing-system
    username: postgres
    password: root
