-- Customers
CREATE TABLE customers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(99) NOT NULL,
    last_name VARCHAR(99) NOT NULL,
    email VARCHAR (255) NOT NULL UNIQUE,
    phone VARCHAR (255)
);

-- Products
CREATE TABLE products (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(199) NOT NULL,
    article VARCHAR(16) NOT NULL UNIQUE,
    unit VARCHAR (255) NOT NULL
);

-- Orders
CREATE TABLE orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INT NOT NULL,
    payment_method VARCHAR,
    order_status VARCHAR,
    created_at TIMESTAMP(6) NOT NULL,
    UNIQUE (customer_id, payment_method, created_at),
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_orders_customer_id ON orders(customer_id);

-- Order Items
-- Binds Orders and Products
CREATE TABLE order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id INT NOT NULL,
    quantity NUMERIC(18, 6),
    price_per_unit NUMERIC(11, 2),
    UNIQUE (order_id, product_id, price_per_unit),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
