apiVersion : apps/v1
kind: Deployment
metadata:
  name: registrar-service-deployment
  labels:
    app: order-processing-system-registrar-service
spec:
  replicas: 1
  selector:
    matchLabels:
      project: order-processing-system-registrar-service
  template:
    metadata:
      labels:
        project: order-processing-system-registrar-service
    spec:
      containers:
        - name: registrar-service
          image: ivangorbunovv/order-processing-system:registrar-service
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: registrar-service
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: order-processing-system-registrar-service
  ports:
    - name      : registrar-service-listener
      protocol  : TCP
      port      : 8081
      targetPort: 8081
  #type: CLusterIP