apiVersion : apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: order-processing-system-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      project: order-processing-system-api-gateway
  template:
    metadata:
      labels:
        project: order-processing-system-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ivangorbunovv/order-processing-system:api-gateway
          ports:
            - containerPort: 8765

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: order-processing-system-api-gateway
  ports:
    - name      : api-gateway-listener
      protocol  : TCP
      port      : 8765
      targetPort: 8765
  #type: CLusterIP