server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GorbunovIvan/order-processing-system-config-repo.git
          username:
          password:
          default-label: master
          search-paths: "{application}"
          clone-on-start: true
